services:
  web:
    build: .
    ports:
      - "8080:5000"
  swagger:
    image: swaggerapi/swagger-ui
    expose:
      - 8080
    ports:
      - 8029:8080
    environment:
      SWAGGER_JSON: /docs/swagger.json
    
 